/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as QuickImport } from './routes/quick'
import { Route as CopilotsImport } from './routes/copilots'
import { Route as AboutImport } from './routes/about'
import { Route as SettingsRouteImport } from './routes/settings/route'
import { Route as DevRouteImport } from './routes/dev/route'
import { Route as IndexImport } from './routes/index'
import { Route as SettingsIndexImport } from './routes/settings/index'
import { Route as ImageCreatorIndexImport } from './routes/image-creator/index'
import { Route as DevIndexImport } from './routes/dev/index'
import { Route as SettingsWebSearchImport } from './routes/settings/web-search'
import { Route as SettingsVideoUrlImport } from './routes/settings/video-url'
import { Route as SettingsUserPersonalInfoImport } from './routes/settings/user-personal-info'
import { Route as SettingsUsageImport } from './routes/settings/usage'
import { Route as SettingsSyncImport } from './routes/settings/sync'
import { Route as SettingsSkillsImport } from './routes/settings/skills'
import { Route as SettingsMemoryImport } from './routes/settings/memory'
import { Route as SettingsMcpImport } from './routes/settings/mcp'
import { Route as SettingsKnowledgeBaseImport } from './routes/settings/knowledge-base'
import { Route as SettingsIntegrationsImport } from './routes/settings/integrations'
import { Route as SettingsHotkeysImport } from './routes/settings/hotkeys'
import { Route as SettingsHooksImport } from './routes/settings/hooks'
import { Route as SettingsGeneralImport } from './routes/settings/general'
import { Route as SettingsDocumentParserImport } from './routes/settings/document-parser'
import { Route as SettingsDefaultModelsImport } from './routes/settings/default-models'
import { Route as SettingsCopilotsImport } from './routes/settings/copilots'
import { Route as SettingsComputerUseImport } from './routes/settings/computer-use'
import { Route as SettingsCommandsImport } from './routes/settings/commands'
import { Route as SettingsChatImport } from './routes/settings/chat'
import { Route as SettingsBrowserAgentImport } from './routes/settings/browser-agent'
import { Route as SettingsAgentsImport } from './routes/settings/agents'
import { Route as SessionSessionIdImport } from './routes/session/$sessionId'
import { Route as DevStorageImport } from './routes/dev/storage'
import { Route as DevModelSelectorImport } from './routes/dev/model-selector'
import { Route as DevCssVarImport } from './routes/dev/css-var'
import { Route as DevContextGeneratorImport } from './routes/dev/context-generator'
import { Route as SettingsProviderRouteImport } from './routes/settings/provider/route'
import { Route as SettingsProviderIndexImport } from './routes/settings/provider/index'
import { Route as SettingsProviderProviderIdImport } from './routes/settings/provider/$providerId'

// Create/Update Routes

const QuickRoute = QuickImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => rootRoute,
} as any)

const CopilotsRoute = CopilotsImport.update({
  id: '/copilots',
  path: '/copilots',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRouteRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const DevRouteRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsIndexRoute = SettingsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const ImageCreatorIndexRoute = ImageCreatorIndexImport.update({
  id: '/image-creator/',
  path: '/image-creator/',
  getParentRoute: () => rootRoute,
} as any)

const DevIndexRoute = DevIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevRouteRoute,
} as any)

const SettingsWebSearchRoute = SettingsWebSearchImport.update({
  id: '/web-search',
  path: '/web-search',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsVideoUrlRoute = SettingsVideoUrlImport.update({
  id: '/video-url',
  path: '/video-url',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsUserPersonalInfoRoute = SettingsUserPersonalInfoImport.update({
  id: '/user-personal-info',
  path: '/user-personal-info',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsUsageRoute = SettingsUsageImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsSyncRoute = SettingsSyncImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsSkillsRoute = SettingsSkillsImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsMemoryRoute = SettingsMemoryImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsMcpRoute = SettingsMcpImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsKnowledgeBaseRoute = SettingsKnowledgeBaseImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsIntegrationsRoute = SettingsIntegrationsImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsHotkeysRoute = SettingsHotkeysImport.update({
  id: '/hotkeys',
  path: '/hotkeys',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsHooksRoute = SettingsHooksImport.update({
  id: '/hooks',
  path: '/hooks',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsGeneralRoute = SettingsGeneralImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsDocumentParserRoute = SettingsDocumentParserImport.update({
  id: '/document-parser',
  path: '/document-parser',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsDefaultModelsRoute = SettingsDefaultModelsImport.update({
  id: '/default-models',
  path: '/default-models',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsCopilotsRoute = SettingsCopilotsImport.update({
  id: '/copilots',
  path: '/copilots',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsComputerUseRoute = SettingsComputerUseImport.update({
  id: '/computer-use',
  path: '/computer-use',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsCommandsRoute = SettingsCommandsImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsChatRoute = SettingsChatImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsBrowserAgentRoute = SettingsBrowserAgentImport.update({
  id: '/browser-agent',
  path: '/browser-agent',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsAgentsRoute = SettingsAgentsImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SessionSessionIdRoute = SessionSessionIdImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRoute,
} as any)

const DevStorageRoute = DevStorageImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => DevRouteRoute,
} as any)

const DevModelSelectorRoute = DevModelSelectorImport.update({
  id: '/model-selector',
  path: '/model-selector',
  getParentRoute: () => DevRouteRoute,
} as any)

const DevCssVarRoute = DevCssVarImport.update({
  id: '/css-var',
  path: '/css-var',
  getParentRoute: () => DevRouteRoute,
} as any)

const DevContextGeneratorRoute = DevContextGeneratorImport.update({
  id: '/context-generator',
  path: '/context-generator',
  getParentRoute: () => DevRouteRoute,
} as any)

const SettingsProviderRouteRoute = SettingsProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsProviderIndexRoute = SettingsProviderIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsProviderRouteRoute,
} as any)

const SettingsProviderProviderIdRoute = SettingsProviderProviderIdImport.update(
  {
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => SettingsProviderRouteRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/copilots': {
      id: '/copilots'
      path: '/copilots'
      fullPath: '/copilots'
      preLoaderRoute: typeof CopilotsImport
      parentRoute: typeof rootRoute
    }
    '/quick': {
      id: '/quick'
      path: '/quick'
      fullPath: '/quick'
      preLoaderRoute: typeof QuickImport
      parentRoute: typeof rootRoute
    }
    '/settings/provider': {
      id: '/settings/provider'
      path: '/provider'
      fullPath: '/settings/provider'
      preLoaderRoute: typeof SettingsProviderRouteImport
      parentRoute: typeof SettingsRouteImport
    }
    '/dev/context-generator': {
      id: '/dev/context-generator'
      path: '/context-generator'
      fullPath: '/dev/context-generator'
      preLoaderRoute: typeof DevContextGeneratorImport
      parentRoute: typeof DevRouteImport
    }
    '/dev/css-var': {
      id: '/dev/css-var'
      path: '/css-var'
      fullPath: '/dev/css-var'
      preLoaderRoute: typeof DevCssVarImport
      parentRoute: typeof DevRouteImport
    }
    '/dev/model-selector': {
      id: '/dev/model-selector'
      path: '/model-selector'
      fullPath: '/dev/model-selector'
      preLoaderRoute: typeof DevModelSelectorImport
      parentRoute: typeof DevRouteImport
    }
    '/dev/storage': {
      id: '/dev/storage'
      path: '/storage'
      fullPath: '/dev/storage'
      preLoaderRoute: typeof DevStorageImport
      parentRoute: typeof DevRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdImport
      parentRoute: typeof rootRoute
    }
    '/settings/agents': {
      id: '/settings/agents'
      path: '/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof SettingsAgentsImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/browser-agent': {
      id: '/settings/browser-agent'
      path: '/browser-agent'
      fullPath: '/settings/browser-agent'
      preLoaderRoute: typeof SettingsBrowserAgentImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/chat': {
      id: '/settings/chat'
      path: '/chat'
      fullPath: '/settings/chat'
      preLoaderRoute: typeof SettingsChatImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/commands': {
      id: '/settings/commands'
      path: '/commands'
      fullPath: '/settings/commands'
      preLoaderRoute: typeof SettingsCommandsImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/computer-use': {
      id: '/settings/computer-use'
      path: '/computer-use'
      fullPath: '/settings/computer-use'
      preLoaderRoute: typeof SettingsComputerUseImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/copilots': {
      id: '/settings/copilots'
      path: '/copilots'
      fullPath: '/settings/copilots'
      preLoaderRoute: typeof SettingsCopilotsImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/default-models': {
      id: '/settings/default-models'
      path: '/default-models'
      fullPath: '/settings/default-models'
      preLoaderRoute: typeof SettingsDefaultModelsImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/document-parser': {
      id: '/settings/document-parser'
      path: '/document-parser'
      fullPath: '/settings/document-parser'
      preLoaderRoute: typeof SettingsDocumentParserImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/hooks': {
      id: '/settings/hooks'
      path: '/hooks'
      fullPath: '/settings/hooks'
      preLoaderRoute: typeof SettingsHooksImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/hotkeys': {
      id: '/settings/hotkeys'
      path: '/hotkeys'
      fullPath: '/settings/hotkeys'
      preLoaderRoute: typeof SettingsHotkeysImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/knowledge-base': {
      id: '/settings/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/settings/knowledge-base'
      preLoaderRoute: typeof SettingsKnowledgeBaseImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/mcp': {
      id: '/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof SettingsMcpImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/memory': {
      id: '/settings/memory'
      path: '/memory'
      fullPath: '/settings/memory'
      preLoaderRoute: typeof SettingsMemoryImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/skills': {
      id: '/settings/skills'
      path: '/skills'
      fullPath: '/settings/skills'
      preLoaderRoute: typeof SettingsSkillsImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/sync': {
      id: '/settings/sync'
      path: '/sync'
      fullPath: '/settings/sync'
      preLoaderRoute: typeof SettingsSyncImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/usage': {
      id: '/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof SettingsUsageImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/user-personal-info': {
      id: '/settings/user-personal-info'
      path: '/user-personal-info'
      fullPath: '/settings/user-personal-info'
      preLoaderRoute: typeof SettingsUserPersonalInfoImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/video-url': {
      id: '/settings/video-url'
      path: '/video-url'
      fullPath: '/settings/video-url'
      preLoaderRoute: typeof SettingsVideoUrlImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/web-search': {
      id: '/settings/web-search'
      path: '/web-search'
      fullPath: '/settings/web-search'
      preLoaderRoute: typeof SettingsWebSearchImport
      parentRoute: typeof SettingsRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexImport
      parentRoute: typeof DevRouteImport
    }
    '/image-creator/': {
      id: '/image-creator/'
      path: '/image-creator'
      fullPath: '/image-creator'
      preLoaderRoute: typeof ImageCreatorIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/provider/$providerId': {
      id: '/settings/provider/$providerId'
      path: '/$providerId'
      fullPath: '/settings/provider/$providerId'
      preLoaderRoute: typeof SettingsProviderProviderIdImport
      parentRoute: typeof SettingsProviderRouteImport
    }
    '/settings/provider/': {
      id: '/settings/provider/'
      path: '/'
      fullPath: '/settings/provider/'
      preLoaderRoute: typeof SettingsProviderIndexImport
      parentRoute: typeof SettingsProviderRouteImport
    }
  }
}

// Create and export the route tree

interface DevRouteRouteChildren {
  DevContextGeneratorRoute: typeof DevContextGeneratorRoute
  DevCssVarRoute: typeof DevCssVarRoute
  DevModelSelectorRoute: typeof DevModelSelectorRoute
  DevStorageRoute: typeof DevStorageRoute
  DevIndexRoute: typeof DevIndexRoute
}

const DevRouteRouteChildren: DevRouteRouteChildren = {
  DevContextGeneratorRoute: DevContextGeneratorRoute,
  DevCssVarRoute: DevCssVarRoute,
  DevModelSelectorRoute: DevModelSelectorRoute,
  DevStorageRoute: DevStorageRoute,
  DevIndexRoute: DevIndexRoute,
}

const DevRouteRouteWithChildren = DevRouteRoute._addFileChildren(
  DevRouteRouteChildren,
)

interface SettingsProviderRouteRouteChildren {
  SettingsProviderProviderIdRoute: typeof SettingsProviderProviderIdRoute
  SettingsProviderIndexRoute: typeof SettingsProviderIndexRoute
}

const SettingsProviderRouteRouteChildren: SettingsProviderRouteRouteChildren = {
  SettingsProviderProviderIdRoute: SettingsProviderProviderIdRoute,
  SettingsProviderIndexRoute: SettingsProviderIndexRoute,
}

const SettingsProviderRouteRouteWithChildren =
  SettingsProviderRouteRoute._addFileChildren(
    SettingsProviderRouteRouteChildren,
  )

interface SettingsRouteRouteChildren {
  SettingsProviderRouteRoute: typeof SettingsProviderRouteRouteWithChildren
  SettingsAgentsRoute: typeof SettingsAgentsRoute
  SettingsBrowserAgentRoute: typeof SettingsBrowserAgentRoute
  SettingsChatRoute: typeof SettingsChatRoute
  SettingsCommandsRoute: typeof SettingsCommandsRoute
  SettingsComputerUseRoute: typeof SettingsComputerUseRoute
  SettingsCopilotsRoute: typeof SettingsCopilotsRoute
  SettingsDefaultModelsRoute: typeof SettingsDefaultModelsRoute
  SettingsDocumentParserRoute: typeof SettingsDocumentParserRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsHooksRoute: typeof SettingsHooksRoute
  SettingsHotkeysRoute: typeof SettingsHotkeysRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsKnowledgeBaseRoute: typeof SettingsKnowledgeBaseRoute
  SettingsMcpRoute: typeof SettingsMcpRoute
  SettingsMemoryRoute: typeof SettingsMemoryRoute
  SettingsSkillsRoute: typeof SettingsSkillsRoute
  SettingsSyncRoute: typeof SettingsSyncRoute
  SettingsUsageRoute: typeof SettingsUsageRoute
  SettingsUserPersonalInfoRoute: typeof SettingsUserPersonalInfoRoute
  SettingsVideoUrlRoute: typeof SettingsVideoUrlRoute
  SettingsWebSearchRoute: typeof SettingsWebSearchRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsProviderRouteRoute: SettingsProviderRouteRouteWithChildren,
  SettingsAgentsRoute: SettingsAgentsRoute,
  SettingsBrowserAgentRoute: SettingsBrowserAgentRoute,
  SettingsChatRoute: SettingsChatRoute,
  SettingsCommandsRoute: SettingsCommandsRoute,
  SettingsComputerUseRoute: SettingsComputerUseRoute,
  SettingsCopilotsRoute: SettingsCopilotsRoute,
  SettingsDefaultModelsRoute: SettingsDefaultModelsRoute,
  SettingsDocumentParserRoute: SettingsDocumentParserRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsHooksRoute: SettingsHooksRoute,
  SettingsHotkeysRoute: SettingsHotkeysRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsKnowledgeBaseRoute: SettingsKnowledgeBaseRoute,
  SettingsMcpRoute: SettingsMcpRoute,
  SettingsMemoryRoute: SettingsMemoryRoute,
  SettingsSkillsRoute: SettingsSkillsRoute,
  SettingsSyncRoute: SettingsSyncRoute,
  SettingsUsageRoute: SettingsUsageRoute,
  SettingsUserPersonalInfoRoute: SettingsUserPersonalInfoRoute,
  SettingsVideoUrlRoute: SettingsVideoUrlRoute,
  SettingsWebSearchRoute: SettingsWebSearchRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev': typeof DevRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/copilots': typeof CopilotsRoute
  '/quick': typeof QuickRoute
  '/settings/provider': typeof SettingsProviderRouteRouteWithChildren
  '/dev/context-generator': typeof DevContextGeneratorRoute
  '/dev/css-var': typeof DevCssVarRoute
  '/dev/model-selector': typeof DevModelSelectorRoute
  '/dev/storage': typeof DevStorageRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/browser-agent': typeof SettingsBrowserAgentRoute
  '/settings/chat': typeof SettingsChatRoute
  '/settings/commands': typeof SettingsCommandsRoute
  '/settings/computer-use': typeof SettingsComputerUseRoute
  '/settings/copilots': typeof SettingsCopilotsRoute
  '/settings/default-models': typeof SettingsDefaultModelsRoute
  '/settings/document-parser': typeof SettingsDocumentParserRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/hooks': typeof SettingsHooksRoute
  '/settings/hotkeys': typeof SettingsHotkeysRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/knowledge-base': typeof SettingsKnowledgeBaseRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/settings/user-personal-info': typeof SettingsUserPersonalInfoRoute
  '/settings/video-url': typeof SettingsVideoUrlRoute
  '/settings/web-search': typeof SettingsWebSearchRoute
  '/dev/': typeof DevIndexRoute
  '/image-creator': typeof ImageCreatorIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/provider/$providerId': typeof SettingsProviderProviderIdRoute
  '/settings/provider/': typeof SettingsProviderIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/copilots': typeof CopilotsRoute
  '/quick': typeof QuickRoute
  '/dev/context-generator': typeof DevContextGeneratorRoute
  '/dev/css-var': typeof DevCssVarRoute
  '/dev/model-selector': typeof DevModelSelectorRoute
  '/dev/storage': typeof DevStorageRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/browser-agent': typeof SettingsBrowserAgentRoute
  '/settings/chat': typeof SettingsChatRoute
  '/settings/commands': typeof SettingsCommandsRoute
  '/settings/computer-use': typeof SettingsComputerUseRoute
  '/settings/copilots': typeof SettingsCopilotsRoute
  '/settings/default-models': typeof SettingsDefaultModelsRoute
  '/settings/document-parser': typeof SettingsDocumentParserRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/hooks': typeof SettingsHooksRoute
  '/settings/hotkeys': typeof SettingsHotkeysRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/knowledge-base': typeof SettingsKnowledgeBaseRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/settings/user-personal-info': typeof SettingsUserPersonalInfoRoute
  '/settings/video-url': typeof SettingsVideoUrlRoute
  '/settings/web-search': typeof SettingsWebSearchRoute
  '/dev': typeof DevIndexRoute
  '/image-creator': typeof ImageCreatorIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/provider/$providerId': typeof SettingsProviderProviderIdRoute
  '/settings/provider': typeof SettingsProviderIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dev': typeof DevRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/copilots': typeof CopilotsRoute
  '/quick': typeof QuickRoute
  '/settings/provider': typeof SettingsProviderRouteRouteWithChildren
  '/dev/context-generator': typeof DevContextGeneratorRoute
  '/dev/css-var': typeof DevCssVarRoute
  '/dev/model-selector': typeof DevModelSelectorRoute
  '/dev/storage': typeof DevStorageRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/browser-agent': typeof SettingsBrowserAgentRoute
  '/settings/chat': typeof SettingsChatRoute
  '/settings/commands': typeof SettingsCommandsRoute
  '/settings/computer-use': typeof SettingsComputerUseRoute
  '/settings/copilots': typeof SettingsCopilotsRoute
  '/settings/default-models': typeof SettingsDefaultModelsRoute
  '/settings/document-parser': typeof SettingsDocumentParserRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/hooks': typeof SettingsHooksRoute
  '/settings/hotkeys': typeof SettingsHotkeysRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/knowledge-base': typeof SettingsKnowledgeBaseRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/settings/user-personal-info': typeof SettingsUserPersonalInfoRoute
  '/settings/video-url': typeof SettingsVideoUrlRoute
  '/settings/web-search': typeof SettingsWebSearchRoute
  '/dev/': typeof DevIndexRoute
  '/image-creator/': typeof ImageCreatorIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/provider/$providerId': typeof SettingsProviderProviderIdRoute
  '/settings/provider/': typeof SettingsProviderIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev'
    | '/settings'
    | '/about'
    | '/copilots'
    | '/quick'
    | '/settings/provider'
    | '/dev/context-generator'
    | '/dev/css-var'
    | '/dev/model-selector'
    | '/dev/storage'
    | '/session/$sessionId'
    | '/settings/agents'
    | '/settings/browser-agent'
    | '/settings/chat'
    | '/settings/commands'
    | '/settings/computer-use'
    | '/settings/copilots'
    | '/settings/default-models'
    | '/settings/document-parser'
    | '/settings/general'
    | '/settings/hooks'
    | '/settings/hotkeys'
    | '/settings/integrations'
    | '/settings/knowledge-base'
    | '/settings/mcp'
    | '/settings/memory'
    | '/settings/skills'
    | '/settings/sync'
    | '/settings/usage'
    | '/settings/user-personal-info'
    | '/settings/video-url'
    | '/settings/web-search'
    | '/dev/'
    | '/image-creator'
    | '/settings/'
    | '/settings/provider/$providerId'
    | '/settings/provider/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/copilots'
    | '/quick'
    | '/dev/context-generator'
    | '/dev/css-var'
    | '/dev/model-selector'
    | '/dev/storage'
    | '/session/$sessionId'
    | '/settings/agents'
    | '/settings/browser-agent'
    | '/settings/chat'
    | '/settings/commands'
    | '/settings/computer-use'
    | '/settings/copilots'
    | '/settings/default-models'
    | '/settings/document-parser'
    | '/settings/general'
    | '/settings/hooks'
    | '/settings/hotkeys'
    | '/settings/integrations'
    | '/settings/knowledge-base'
    | '/settings/mcp'
    | '/settings/memory'
    | '/settings/skills'
    | '/settings/sync'
    | '/settings/usage'
    | '/settings/user-personal-info'
    | '/settings/video-url'
    | '/settings/web-search'
    | '/dev'
    | '/image-creator'
    | '/settings'
    | '/settings/provider/$providerId'
    | '/settings/provider'
  id:
    | '__root__'
    | '/'
    | '/dev'
    | '/settings'
    | '/about'
    | '/copilots'
    | '/quick'
    | '/settings/provider'
    | '/dev/context-generator'
    | '/dev/css-var'
    | '/dev/model-selector'
    | '/dev/storage'
    | '/session/$sessionId'
    | '/settings/agents'
    | '/settings/browser-agent'
    | '/settings/chat'
    | '/settings/commands'
    | '/settings/computer-use'
    | '/settings/copilots'
    | '/settings/default-models'
    | '/settings/document-parser'
    | '/settings/general'
    | '/settings/hooks'
    | '/settings/hotkeys'
    | '/settings/integrations'
    | '/settings/knowledge-base'
    | '/settings/mcp'
    | '/settings/memory'
    | '/settings/skills'
    | '/settings/sync'
    | '/settings/usage'
    | '/settings/user-personal-info'
    | '/settings/video-url'
    | '/settings/web-search'
    | '/dev/'
    | '/image-creator/'
    | '/settings/'
    | '/settings/provider/$providerId'
    | '/settings/provider/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevRouteRoute: typeof DevRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CopilotsRoute: typeof CopilotsRoute
  QuickRoute: typeof QuickRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
  ImageCreatorIndexRoute: typeof ImageCreatorIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevRouteRoute: DevRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CopilotsRoute: CopilotsRoute,
  QuickRoute: QuickRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
  ImageCreatorIndexRoute: ImageCreatorIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dev",
        "/settings",
        "/about",
        "/copilots",
        "/quick",
        "/session/$sessionId",
        "/image-creator/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dev": {
      "filePath": "dev/route.tsx",
      "children": [
        "/dev/context-generator",
        "/dev/css-var",
        "/dev/model-selector",
        "/dev/storage",
        "/dev/"
      ]
    },
    "/settings": {
      "filePath": "settings/route.tsx",
      "children": [
        "/settings/provider",
        "/settings/agents",
        "/settings/browser-agent",
        "/settings/chat",
        "/settings/commands",
        "/settings/computer-use",
        "/settings/copilots",
        "/settings/default-models",
        "/settings/document-parser",
        "/settings/general",
        "/settings/hooks",
        "/settings/hotkeys",
        "/settings/integrations",
        "/settings/knowledge-base",
        "/settings/mcp",
        "/settings/memory",
        "/settings/skills",
        "/settings/sync",
        "/settings/usage",
        "/settings/user-personal-info",
        "/settings/video-url",
        "/settings/web-search",
        "/settings/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/copilots": {
      "filePath": "copilots.tsx"
    },
    "/quick": {
      "filePath": "quick.tsx"
    },
    "/settings/provider": {
      "filePath": "settings/provider/route.tsx",
      "parent": "/settings",
      "children": [
        "/settings/provider/$providerId",
        "/settings/provider/"
      ]
    },
    "/dev/context-generator": {
      "filePath": "dev/context-generator.tsx",
      "parent": "/dev"
    },
    "/dev/css-var": {
      "filePath": "dev/css-var.tsx",
      "parent": "/dev"
    },
    "/dev/model-selector": {
      "filePath": "dev/model-selector.tsx",
      "parent": "/dev"
    },
    "/dev/storage": {
      "filePath": "dev/storage.tsx",
      "parent": "/dev"
    },
    "/session/$sessionId": {
      "filePath": "session/$sessionId.tsx"
    },
    "/settings/agents": {
      "filePath": "settings/agents.tsx",
      "parent": "/settings"
    },
    "/settings/browser-agent": {
      "filePath": "settings/browser-agent.tsx",
      "parent": "/settings"
    },
    "/settings/chat": {
      "filePath": "settings/chat.tsx",
      "parent": "/settings"
    },
    "/settings/commands": {
      "filePath": "settings/commands.tsx",
      "parent": "/settings"
    },
    "/settings/computer-use": {
      "filePath": "settings/computer-use.tsx",
      "parent": "/settings"
    },
    "/settings/copilots": {
      "filePath": "settings/copilots.tsx",
      "parent": "/settings"
    },
    "/settings/default-models": {
      "filePath": "settings/default-models.tsx",
      "parent": "/settings"
    },
    "/settings/document-parser": {
      "filePath": "settings/document-parser.tsx",
      "parent": "/settings"
    },
    "/settings/general": {
      "filePath": "settings/general.tsx",
      "parent": "/settings"
    },
    "/settings/hooks": {
      "filePath": "settings/hooks.tsx",
      "parent": "/settings"
    },
    "/settings/hotkeys": {
      "filePath": "settings/hotkeys.tsx",
      "parent": "/settings"
    },
    "/settings/integrations": {
      "filePath": "settings/integrations.tsx",
      "parent": "/settings"
    },
    "/settings/knowledge-base": {
      "filePath": "settings/knowledge-base.tsx",
      "parent": "/settings"
    },
    "/settings/mcp": {
      "filePath": "settings/mcp.tsx",
      "parent": "/settings"
    },
    "/settings/memory": {
      "filePath": "settings/memory.tsx",
      "parent": "/settings"
    },
    "/settings/skills": {
      "filePath": "settings/skills.tsx",
      "parent": "/settings"
    },
    "/settings/sync": {
      "filePath": "settings/sync.tsx",
      "parent": "/settings"
    },
    "/settings/usage": {
      "filePath": "settings/usage.tsx",
      "parent": "/settings"
    },
    "/settings/user-personal-info": {
      "filePath": "settings/user-personal-info.tsx",
      "parent": "/settings"
    },
    "/settings/video-url": {
      "filePath": "settings/video-url.tsx",
      "parent": "/settings"
    },
    "/settings/web-search": {
      "filePath": "settings/web-search.tsx",
      "parent": "/settings"
    },
    "/dev/": {
      "filePath": "dev/index.tsx",
      "parent": "/dev"
    },
    "/image-creator/": {
      "filePath": "image-creator/index.tsx"
    },
    "/settings/": {
      "filePath": "settings/index.tsx",
      "parent": "/settings"
    },
    "/settings/provider/$providerId": {
      "filePath": "settings/provider/$providerId.tsx",
      "parent": "/settings/provider"
    },
    "/settings/provider/": {
      "filePath": "settings/provider/index.tsx",
      "parent": "/settings/provider"
    }
  }
}
ROUTE_MANIFEST_END */
